name: flutter_go
description: flutter_go

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  intl: ^0.15.7
  path: ^1.6.2

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  flutter_web_test: any
  test: ^1.6.3
  build_daemon: ^1.0.0
  idb_shim: any
  event_bus: any
  key_value_store_web: ^1.0.0
  http: ^0.12.0+2
  jsonp: ^3.0.1
  convert: any
  #flutter_html_view: ^0.5.11
  #flutter_html: any

dependency_overrides:
  flutter_web:
    #path: packages/flutter_web
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_test:
    #path: packages/flutter_web_test
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
  flutter_web_ui:
    #path: packages/flutter_web_ui
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui